### ISSUE TITLE
Generate favicon related resources

### ISSUE THREAD

**Issue by jamesatheyDDS** [deptofdefense/move.mil#205]
Using something like https://realfavicongenerator.net/, generate all favicon resources (including "touch" icons used by iOS). Will reduce the 404s seen in production by iOS devices hitting the site.

**Comment by jgarber623-gov** [comment]
We've got a `favicon.ico`. What we're lacking are the various `apple-touch-icon` variants.

**Comment by jgarber623-gov** [comment]
Correction: we're doing the following in the layout's markup:

```erb
<%= tag.link href: asset_path('ustranscom-emblem-256x256.png'), rel: 'apple-shortcut-icon' %>
<%= tag.link href: asset_path('ustranscom-emblem-256x256.png'), rel: 'shortcut icon' %>
```

That should inform browsers where to find shortcut-style icons. `favicon.ico` is a fallback since so many Web browsers will look for that irrespective of the presence of a `<link rel="shortcut icon">` in the markup.

So… that said, I think this one is addressed to the degree that we need to worry about it.

**Comment by jgarber623-gov** [comment]
From the error logs, here's a list of common file names being requested:

- apple-touch-icon-120x120-precomposed.png
- apple-touch-icon-120x120.png
- apple-touch-icon-precomposed.png
- apple-touch-icon.png
