### ISSUE TITLE
Packers are more important than movers. 

### ISSUE THREAD

**Issue by jdsager** [deptofdefense/move.mil#303]
Request subject be removed all together...located at "Moving Guide - Moving Tips - During the Move (Packing and Unloading) - Packers are more important than movers"

## Checklist

I have…

- [x] described in detail below both the behavior I expected and the behavior I observed.
- [ ] thoroughly outlined below the steps to reproduce this issue, including relevant technical details (e.g. device, operating system, browser, browser version).
- [x] attached screenshots illustrating relevant behavior.

## Expected Behavior

_Summarize expected behavior._ Navy MCO comment asking for complete removal "I believe there is so much wrong with this information being published that it should be removed completely.   A member is already suffering a financial impact with a move, why would you even suggest that in order to get a good move they need to buy lunch and knowing they are hiring someone off the street to load doesn't present a warm fuzzy."                                                

## Observed Behavior

_Summarize observed behavior._ Paragraph currently reads... "Most people focus their efforts on the movers. Movers can be picked up off the street on the day of a move. Packers are the experienced professionals. They can make sure your breakable stuff has the best chance of arriving unbroken. Learn their names. Offer to run out and get them a lunch and make sure the fridge is stocked with waters and other beverages. Praise the nice job that they are doing or start up some small talk — and they typically do a nicer job." 

## Steps to Reproduce

To reproduce this issue…

1. _Describe step one._
1. _Describe step two._
1. _etc. etc. etc._

## Screenshots

_Attach relevant screenshots here._
[Packers are more important than movers.pdf](https://github.com/deptofdefense/move.mil/files/1640815/Packers.are.more.important.than.movers.pdf)

**Comment by hatueyustc** [comment]
Add "USTC Reviewed label".  Approved minor wording change. 

Expected behavior "Most people focus their efforts on the movers. Movers can be picked up off the street on the day of a move. Packers are the experienced professionals. They can make sure your breakable stuff has the best chance of arriving unbroken. Learn their names. Consider offering them lunch and make sure the fridge is stocked with water and other beverages. Praise the nice job that they are doing or start up some small talk — and they typically do a nicer job."
