### ISSUE TITLE
Remember you can "fire" your mover and packers.

### ISSUE THREAD

**Issue by jdsager** [deptofdefense/move.mil#304]
Located at:  Moving Guide - Moving Tips - During the Move (Packing and Unloading) - Remember you can "fire" your mover and packers.

I recommend you change the subject title.  Otherwise, you are going to have people playing Donald Trump and actually firing the mover on the spot…then what?  Just imagine that member that cannot get someone at the PPSO, they may take this heading seriously without knowing the ramifications.  

## Checklist

I have…

- [x] described in detail below both the behavior I expected and the behavior I observed.
- [ ] thoroughly outlined below the steps to reproduce this issue, including relevant technical details (e.g. device, operating system, browser, browser version).
- [x] attached screenshots illustrating relevant behavior.

## Expected Behavior - Change title to "If something seems to be going very, very wrong with your move" 

Reword to:  "Movers are disagreeing, things are getting damaged, or you feel uncomfortable, etc., call your local Personal Property Processing Office (PPPO) immediately! They will help sort things out, to include they may be able to send a representative to the residence. "

_Summarize expected behavior._ Retitle "Remember you can "fire" your mover and packers"

## Observed Behavior

_Summarize observed behavior._  Titled "Remember you can "fire" your mover and packers."  If something seems to be going very, very wrong on your move (movers are fighting, things are getting damaged, you feel uncomfortable, etc.) call your local personal property office (PPPO) immediately! They will send a representative over to sort things out. Don’t become another nightmare move story!"

## Steps to Reproduce

To reproduce this issue…

1. _Moving Guide - Moving Tips - During the Move (Packing and Unloading) - Remember you can "fire" your mover and packers.
1. _Describe step two._
1. _etc. etc. etc._

## Screenshots

_Attach relevant screenshots here._
[Remember you can fire you mover and packers.pdf](https://github.com/deptofdefense/move.mil/files/1640875/Remember.you.can.fire.you.mover.and.packers.pdf)

**Comment by hatueyustc** [comment]
Approved with a change.  Please add label "USTC Reviewed."  

Minor language updates below to align customer expectations to levels of PPPO support ("will" to "may", etc):

Expected behavior. Titled "Remember you can "fire" your mover and packers." If something seems to be going very, very wrong on your move (movers are fighting, things are getting damaged, you feel uncomfortable, etc.) call your local personal property office (PPPO) immediately! They will help sort things out and may send a representative over if needed. Don’t become a nightmare move story!"
