### ISSUE TITLE
NTS highlighted for CONUS PCS and paragraph verbiage change 

### ISSUE THREAD

**Issue by jdsager** [deptofdefense/move.mil#317]
Submitted by USTC J54 PI: Located under Moving Guide - Moving with the Military Overview – Move Types -  Non-Temporary Storage (NTS)  (paragraph verbiage change within  "Upon receiving a new assignment/orders, and when you return and have") ALSO "Green highlight with the checkmark for NTS Approved for: CONUS"

## Checklist

I have…

- [x] described in detail below both the behavior I expected and the behavior I observed.
- [ ] thoroughly outlined below the steps to reproduce this issue, including relevant technical details (e.g. device, operating system, browser, browser version).
- [x] attached screenshots illustrating relevant behavior.

## Expected Behavior - Paragraph changed to:  Non-temporary storage (NTS) is long-term storage of your belongings used generally in lieu of shipping your items to your new duty station. Expect the storage location to be located near the origin (pickup) location where items may remain for the duration of your tour. Upon receiving a new assignment/orders, and when you have established a new address, you can request retrieval and shipment of your stored belongings. 

ALSO "Green highlight with the checkmark for NTS Approved for: CONUS"  statement is correct with the verbiage ‘exceptions may apply’.

_Summarize expected behavior._  minor verbiage change as noted above and green highlight NTS Approved for CONUS 

## Observed Behavior - Non-temporary storage (NTS) is long-term storage of your belongings used generally in lieu of shipping your items to your new duty station. Expect the storage location to be located near the origin (pickup) location where items may remain for the duration of your tour. When you return and have established a new address, you can request retrieval and shipment of your stored belongings once you have established a new address.

_Summarize observed behavior._

## Steps to Reproduce

To reproduce this issue…

1. _Located under Moving Guide - Moving with the Military Overview – Move Types -  Non-Temporary Storage (NTS) almost for the ways at the bottom
1. _Describe step two._
1. _etc. etc. etc._

## Screenshots

_Attach relevant screenshots here._
[NTS para  GitHub # 317.pdf](https://github.com/deptofdefense/move.mil/files/1647860/NTS.para.GitHub.317.pdf)

**Comment by jillesmith1** [comment]
VALID--for dev action. 

1.  **Replace** entire paragraph to read:  Non-temporary storage (NTS) is long-term storage of your belongings used generally instead of shipping your items to your new duty station. Expect the storage location to be located near the origin (pickup) location where items may remain for the duration of your tour. When you return and have established a new address, you can request retrieval and shipment of your stored belongings. There may be restrictions on CONUS NTS, so be sure to contact your transportation office if you have any questions." 

2.  **Color** "Permanent Change of Station (PCS), exceptions may apply" YELLOW; retain X mark

**Comment by hatueyustc** [comment]
Please add "USTC Reviewed label"
