### ISSUE TITLE
Minor rewrite "Make unpacking into a family game - how many boxes can each person unpack in an hour"

### ISSUE THREAD

**Issue by jdsager** [deptofdefense/move.mil#321]
Moving Guide - Moving Tips - At Your Destination - 4th one down "Make unpacking into a family game - how many boxes can each person unpack in an hour"

## Checklist

I have…

- [x] described in detail below both the behavior I expected and the behavior I observed.
- [ ] thoroughly outlined below the steps to reproduce this issue, including relevant technical details (e.g. device, operating system, browser, browser version).
- [x] attached screenshots illustrating relevant behavior.

## Expected Behavior-  Rewrite to "Unpacking boxes can get overwhelming. Race yourself to see how many boxes you can unpack in an hour. Or tell your kids that you are going to work together to unpack these four boxes then go to the new park. Keep moving forward. What are you going to do with all those boxes? Remember the movers are only required to take boxes etc., away that are unpacked on the day of delivery  or you can always offer them up to any neighbors that might be getting ready for a move."

_Summarize expected behavior._

## Observed Behavior - rewrite of "Boxes can get overwhelming. Race yourself to see how many boxes you can unpack in an hour. Or tell your kids that you are going to work together to unpack these four boxes then go to the new park. Keep moving forward. What are you going to do with all those boxes? Remember the movers will come back once to take them away for your or you can always offer them up to any neighbors that might be getting ready for a move."

_Summarize observed behavior._

## Steps to Reproduce

To reproduce this issue…

1. _  Moving Guide - Moving Tips - At Your Destination - 4th one down "Make unpacking into a family game - how many boxes can each person unpack in an hour"
1. _Describe step two._
1. _etc. etc. etc._

## Screenshots

_Attach relevant screenshots here._
[Box can get Overwhelming #321.pdf](https://github.com/deptofdefense/move.mil/files/1652548/Box.can.get.Overwhelming.321.pdf)

**Comment by jillesmith1** [comment]
VALID--for dev action. Change the sixth sentence to read, "Remember the movers might come back once to take them away for you or you can always offer them up to any neighbors that might be getting ready for a move."

**Comment by hatueyustc** [comment]
Approved, add label "USTC Reviewed"  Change as the entire paragraph to the following (only the ending was updated).   Expected Behavior- Rewrite to "Unpacking boxes can get overwhelming. Race yourself to see how many boxes you can unpack in an hour. Or tell your kids that you are going to work together to unpack these four boxes then go to the new park. Keep moving forward. What are you going to do with all those boxes? Remember the movers are only required to take boxes away that are unpacked on the day of delivery, although they may choose to come back once to take them away.  You can always offer them up to any neighbors that might be getting ready for a move."
