### ISSUE TITLE
Title change "Nightmare Moves" 

### ISSUE THREAD

**Issue by jdsager** [deptofdefense/move.mil#323]
Moving Guide - Nightmare Moves - haven't met anyone that agrees with the title "Nightmare Moves" should be on an official DoD site 

## Checklist

I have…

- [x] described in detail below both the behavior I expected and the behavior I observed.
- [ ] thoroughly outlined below the steps to reproduce this issue, including relevant technical details (e.g. device, operating system, browser, browser version).
- [x] attached screenshots illustrating relevant behavior.

## Expected Behavior - Change to "Moving Stories" as that is what they are 

_Summarize expected behavior._

## Observed Behavior "Nightmare Moves" title is too negative in preparing people for their move experience

_Summarize observed behavior._

## Steps to Reproduce

To reproduce this issue…

1. _ Moving Guide - Nightmare Moves - haven't met anyone that agrees with the title "Nightmare Moves" should be on an official DoD site 
1. _Describe step two._
1. _etc. etc. etc._

## Screenshots

_Attach relevant screenshots here._ 
[Nightmare Moves #323.pdf](https://github.com/deptofdefense/move.mil/files/1652662/Nightmare.Moves.323.pdf)

**Comment by jillesmith1** [comment]
ELEVATE--for TCJ4-H decision.

**Comment by hatueyustc** [comment]
Approved, please add USTC Reviewed label and change to "Moving stories."

**Comment by schustdj** [comment]
This is not a comment on this issue per se (nightmare moves stands out to be sure), but it came to mind that the more we finesse language around things that are personal--like moving yourself / you & your family, and what can go wrong--the less credibility the site will have with the target audience. Most of the people I have met who serve in the military don't really believe in the thin veneer of perfection that the military sometimes puts on things. Ceding control of that narrative in order to be more effective in the long run is not something the military does well either. Again, I am not disagreeing with this change.

**Comment by jillesmith1** [comment]
@schustdj

**Comment by Elliottdotgov** [comment]
This request represents the opinion of those operating the program and not the needs of the users reading the information. Watering down the language will do nothing but reduce the site's credibility with users. Let's be clear: this is how Personal Property and PCSing is discussed by many Service Members. Everyone knows of a colleague or friend's nightmare move, if they didn't experience one themselves. Gen McDew said this himself: we should not try to sugar coat the moving experience. That is spot on. We need to address the issues head on. Watering down the language is part of the path that lead us to a failed message on archive.move.mil. 

Ultimately this request is contrary to the overall redesign of move.mil. If anyone objects to this path and General McDew's intent here, please find me.
