### ISSUE TITLE
FAQ - After The Move - Last FAQ - What type of Survey ... rewrite 

### ISSUE THREAD

**Issue by jdsager** [deptofdefense/move.mil#350]
USTCJ54-PI inputs considered - To better clarify first two sentences... 

## Checklist

I have…

- [ ] described in detail below both the behavior I expected and the behavior I observed.
- [ ] thoroughly outlined below the steps to reproduce this issue, including relevant technical details (e.g. device, operating system, browser, browser version).
- [ ] attached screenshots illustrating relevant behavior.

## Expected Behavior To clarify first two sentences... Rewrite to "After delivery, you are required to fill out the Customer Satisfaction Survey (CSS). When you accomplish the CSS providing feedback, this goes directly to the Personal Property Processing Offices and effects the distribution of future personal property shipments to that moving company. Be honest and leave comments  – if they were a great mover we want to make sure they get the chance to work with members and their families in the future. If they were not so great… we want to make sure they don’t receive future opportunities."

_Summarize expected behavior._

## Observed Behavior - At the end of your move, it’s highly recommended that you take time to fill out the customer satisfaction survey at the end. This provides the property offices with direct feedback on your moving company. Be honest and leave comments – if they were a great mover we want to make sure they get the chance to work with members and their families in the future. If they were not so great… we want to make sure they don’t get any future opportunities to mess things up.

_Summarize observed behavior._

## Steps to Reproduce

To reproduce this issue…

1. _  FAQ After the Move - last FAQ 
1. _Describe step two._
1. _etc. etc. etc._

## Screenshots

_Attach relevant screenshots here._
[Expected Survey rewrite #350.pdf](https://github.com/deptofdefense/move.mil/files/1669109/Expected.Survey.rewrite.350.pdf)

**Comment by schustdj** [comment]
The DTR states that (Part IV, CH 403, Section C, Paragraph 5a) "Surveys must be completed on shipments that have been delivered to customers." There are some other requirements in paragraph 5, but my question is:

Are systems and processes in place to support a 100% return rate on customer satisfaction surveys? It is my understanding that we throw out surveys for NTS shipments--because the handle-in and handle-out of the household goods are done by two different entities in two different systems--yet we petition the customer to take the survey anyway. Imagine being asked to take a survey that the program asking you already knew they were going to throw away.

I think this portion of the DTR should be re-written for consistency. By that I mean we can't on the one hand say that we require all customers to take a survey for every shipment, and then enforce statistical significance on the TSPs (for if all shipments get a survey why should numbers be defined for BVS calculation), all without having the enforcement mechanism to provide the survey response rate for which we say we are looking.

If I stand alone here, I would recommend that the second sentence of the proposed language to be revised to read, "The feedback you provide in your survey goes to the Personal Property Processing Office that coordinated your current move for their awareness, and also affects the distribution of future household goods shipments to the company who was awarded your shipment."

**Comment by jillesmith1** [comment]
To your question, schustdj, valid points all. DTR IV says, “I understand that I am required to complete the DPS Customer Satisfaction Survey (CSS) upon completion of my shipment. Failure to do so may result in my Service being notified.” If they don't do the survey and the Service is notified (by whom, anyway?), what happens?

**Comment by Elliottdotgov** [comment]
After speaking with many JPPSOs and Service reps, this is not something they enforce at all, nor is it something USTC has the authority to enforce. Ultimately, this might be a thing that is nice to have as is written in policy but without authority to enforce or action on the part of the Services for their members, this discussion is moot. 

We will address improving participation in the CSS using different methods in the Prototype. The text in this issue will stay as is on move.mil.

**Comment by jillesmith1** [comment]
Concur.
